### ISSUE TITLE
CONTENT OF GITHUB NOTEBOOKS NOT VISIBLE

### ISSUE THREAD

**Issue by Vedant-Kalia** [Pierian-Data/Complete-Python-3-Bootcamp#248] opened 2020-08-27 15:58 UTC
As i opened the homework problems of methods and functions , it wasn't visible. Later I realised it wasn't opening for any other topic as well. Kindly look into this matter and fix it to avoid any delay in our learning.

**Comment by jefhar** [comment] 2020-08-27 16:01
Duplicate of issues #238 #239 #240 #241 #242 #243 #244 #245 #246 #247

**Comment by Pierian-Data** [comment] 2020-08-27 17:10
The notebooks here are always up and are visible for me, I just checked and can see the notebooks myself right now. Even if you have any issues viewing here on GitHub you can always **simply download the notebooks locally with the green button on the repo page as discussed and shown in the video lectures.** I am closing this issue since anyone can simply download the notebooks and run locally, if you are unsure about how to do that, please watch the setup and jupyter notebook lectures instead of posting an issue here, since it is not an issue with github or the notebooks. Also please keep  in mind we have answered this exact question multiple times already in the QA Forums on Udemy, so all you need to do is search the existing questions on the forums to quickly see the answers.

**Closed by Pierian-Data** 2020-08-27 17:10 UTC

**Comment by atena5101** [comment] 2020-08-30 00:51
Tankyou

**Comment by atena5101** [comment] 2020-08-30 00:51
# 238 # 239 # 240 # 241 # 242 # 243 # 244 # 245 # 246 # 247

**Comment by atena5101** [comment] 2020-08-30 18:55
در تاریخ یکشنبه ۳۰ اوت ۲۰۲۰،‏ ۵:۲۱ atena5101 <notifications@github.com>
نوشت:

**Comment by atena5101** [comment] 2020-08-30 18:56
در تاریخ یکشنبه ۳۰ اوت ۲۰۲۰،‏ ۲۳:۲۵ atena5101 <notifications@github.com>
نوشت:

**Comment by atena5101** [comment] 2020-08-30 19:01
در تاریخ یکشنبه ۳۰ اوت ۲۰۲۰،‏ ۲۳:۲۶ atena5101 <notifications@github.com>
نوشت:
